<?php
/**
 * Single post template (reviews, guides, explainers).
 *
 * Content column is capped at 720px; the auto-generated TOC is extracted
 * into a sticky right rail on desktop. Lessons share this template.
 *
 * @package w3d
 */

get_header();

while ( have_posts() ) :
	the_post();

	$cats = get_the_category();

	ob_start();
	the_content();
	w3d_lesson_nav();
	$main = (string) ob_get_clean();

	$toc_html = '';
	if ( preg_match( '#<nav class="w3d-toc".*?</nav>#si', $main, $m ) ) {
		$toc_html = $m[0];
		$main     = str_replace( $m[0], '', $main );
	}
	?>
	<header class="w3d-single-hero">
		<div class="w3d-hero-inner">
			<div class="w3d-hero-main">
				<?php w3d_breadcrumbs(); ?>

				<?php if ( ! empty( $cats ) ) : ?>
					<div class="w3d-post-cats">
						<a class="w3d-card-cat" href="<?php echo esc_url( get_category_link( $cats[0] ) ); ?>"><?php echo esc_html( $cats[0]->name ); ?></a>
					</div>
				<?php endif; ?>

				<h1 class="w3d-post-title"><?php the_title(); ?></h1>

				<p class="w3d-post-meta-top">
					<a href="<?php echo esc_url( get_author_posts_url( get_the_author_meta( 'ID' ) ) ); ?>" rel="author">By <?php the_author(); ?></a>
					&middot; <?php echo esc_html( get_the_date() ); ?>
					<?php if ( get_the_modified_time( 'U' ) > get_the_time( 'U' ) ) : ?>
						&middot; Updated <time datetime="<?php echo esc_attr( get_the_modified_time( 'c' ) ); ?>"><?php echo esc_html( get_the_modified_date() ); ?></time>
					<?php endif; ?>
				</p>
			</div>
		</div>
	</header>

	<div class="w3d-wrap w3d-single-body">
		<div class="w3d-post-layout">
			<div class="w3d-archive-band" aria-hidden="true">
				<div class="w3d-archive-band-inner"></div>
			</div>

			<div class="w3d-content entry-content">
				<?php echo $main; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- filters already applied by the_content(). ?>
			</div>

			<?php if ( $toc_html ) : ?>
				<aside class="w3d-toc-rail" aria-label="<?php esc_attr_e( 'Table of contents', 'w3d' ); ?>">
					<?php echo $toc_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by w3d_lesson_toc(). ?>
				</aside>
			<?php endif; ?>
		</div>

		<?php
		if ( 'post' === get_post_type() ) :
			$related = get_posts( array(
				'post_type'      => 'post',
				'post_status'    => 'publish',
				'posts_per_page' => 3,
				'post__not_in'   => array( get_the_ID() ),
				'orderby'        => 'rand',
			) );
			if ( $related ) :
				?>
				<aside class="w3d-related" aria-label="<?php esc_attr_e( 'Related articles', 'w3d' ); ?>">
					<h2><?php esc_html_e( 'Keep reading', 'w3d' ); ?></h2>
					<div class="w3d-learn-grid">
						<?php
						foreach ( $related as $rel_post ) {
							echo w3d_rel_card( 'Guide', $rel_post->ID ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
						}
						?>
					</div>
				</aside>
			<?php endif; ?>
		<?php endif; ?>
	</div>

<?php endwhile; ?>

<?php
get_footer();